server:
  port: 8442

spring:
  profiles:
    default:
      default
  data:
    rest:
      base-path: /data-api
  datasource:
    generate-unique-name: false
    name: tacocloud
  h2:
    console.enabled: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: ${FACEBOOK_CLIENT_ID}
            clientSecret: ${FACEBOOK_CLIENT_SECRET}
            scope: email, public_profile
pagination:
  tacoPageSize: 10