spring:
  data:
    cassandra:
      keyspace-name: tacoscloud
      schema-action: recreate
      local-datacenter: datacenter1
      contact-points:
        - casshost-1.tacocloud.com
        - casshost-2.tacocloud.com
        - casshost-3.tacocloud.com
      port: 9043
      username: tacocloud
      password: s3cr3tP455w0rd
