server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: passkey
    key-password: passkey

spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  h2:
    console.enabled: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: ${FACEBOOK_CLIENT_ID}
            clientSecret: ${FACEBOOK_CLIENT_SECRET}
            scope: email, public_profile
