spring:
  data:
    cassandra:
      keyspace-name: tacocloud
      schema-action: recreate
      local-datacenter: datacenter1
      port: 9043
      request:
        timeout: 10s
server:
  port: 8081