server:
  port: 9090
spring:
  security:
    oauth2:
      client:
        registration:
          taco-admin-client:
            provider: tacocloud
            client-id: taco-admin-client
            client_secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9090/login/oauth2/code/{registrationId}"
            scope: writeIngredients,deleteIngredients,openid
        provider:
          tacocloud:
            issuer-uri: http://127.0.0.1:9010
            authorization-uri: http://127.0.0.1:9010/oauth2/authorize
            token-uri: http://127.0.0.1:910/oauth2/token
            jwk-set-uri: http://127.0.0.1:9010/oauth2/jwks
            user-info-uri: http://127.0.0.1:9010/userinfo
            user-name-attribute: sub
logging:
  level:
    root: DEBUG